#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Chromium executable
#
if [[ -n "$(which chromium 2>/dev/null)" ]]; then
    BROWSER_PATH="$(which chromium)"
elif [[ -n "$(which chrome 2>/dev/null)" ]]; then
    BROWSER_PATH="$(which chrome)"
elif [[ -n "$(which brave 2>/dev/null)" ]]; then
    BROWSER_PATH="$(which brave)"
elif [[ -n "$(which msedge 2>/dev/null)" ]]; then
    BROWSER_PATH="$(which msedge)"
else
    BROWSER_PATH=""
fi

# Launch browser
#
if [[ -n "$BROWSER_PATH" ]]; then
    exec "$BROWSER_PATH" --user-data-dir="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/browser \
        --proxy-server=http://localhost:8080 "$@"
else
    echo "Browser executable not found!"
    exit 1
fi
