#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Chromium executable
#
CHROMIUM_PATH="$(unmask_executable chromium)"

# Launch Chromium
#
if [[ -n "$CHROMIUM_PATH" ]]; then
    exec "$CHROMIUM_PATH" --user-data-dir="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/browser \
        --proxy-server=http://localhost:8080 "$@"
else
    echo "Chromium executable not found!"
    exit 1
fi
