#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Burp Suite executable
#
if [[ "$(uname -s)" == "Darwin" ]]; then
    MACOS_APP_PATH="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/macOS/Applications

    if [[ -d "$MACOS_APP_PATH/Burp Suite Professional.app" ]]; then
        BURP_SUITE_PATH="$MACOS_APP_PATH/Burp Suite Professional.app"/Contents/MacOS/JavaApplicationStub
    elif [[ -d "$MACOS_APP_PATH/Burp Suite Community Edition.app" ]]; then
        BURP_SUITE_PATH="$MACOS_APP_PATH/Burp Suite Community Edition.app"/Contents/MacOS/JavaApplicationStub
    fi
else
    BURP_SUITE_PATH="$(unmask_executable burpsuite)"
fi

# Launch Burp Suite
#
if [[ -n "$BURP_SUITE_PATH" ]]; then
    exec "$BURP_SUITE_PATH" --data-dir="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/BurpSuite \
        --user-config-file="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/BurpSuite/UserConfig.json \
        --disable-auto-update "$@"
else
    echo "Real Burp Suite executable not found!"
    exit 1
fi
