#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Burp Suite paths
#
BURP_SUITE_DATA_PATH="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/BurpSuite

if [[ "$(uname -s)" == "Darwin" ]]; then
    BURP_SUITE_PATH="$(get_direnv_path "$(dirname "$(realpath "$0")")")/appdata/macOS/Applications/Burp Suite Community Edition.app"/Contents/MacOS/JavaApplicationStub
else
    BURP_SUITE_PATH="$(unmask_executable burpsuite)"
fi

# Launch Burp Suite
#
if [[ -n "$BURP_SUITE_PATH" ]]; then
    exec "$BURP_SUITE_PATH" --data-dir="$BURP_SUITE_DATA_PATH" \
        --user-config-file="$BURP_SUITE_DATA_PATH"/UserConfigCommunity.json \
        --disable-auto-update "$@"
else
    echo "Real Burp Suite executable not found!"
    exit 1
fi
