#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Caido CLI executable
#
CAIDO_CLI_PATH="$(unmask_executable caido-cli)"

# Launch Caido CLI
#
if [[ -n "$CAIDO_CLI_PATH" ]]; then
    exec "$CAIDO_CLI_PATH" --data-path "$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/caido "$@"
else
    echo "Real Caido CLI executable not found!"
    exit 1
fi
