#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Chromium executable
#
if [[ "$(uname -s)" == "Darwin" ]]; then
    CHROMIUM_PATH="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/macOS/Applications/Chromium.app/Contents/MacOS/Chromium
else
    CHROMIUM_PATH="$(unmask_executable chromium)"
fi

# Launch Chromium
#
if [[ -n "$CHROMIUM_PATH" ]]; then
    exec "$CHROMIUM_PATH" --user-data-dir="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/chromium \
        --proxy-server=http://localhost:8080 "$@"
else
    echo "Real Chromium executable not found!"
    exit 1
fi
