#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine environment path
#
ENVIRONMENT_PATH="$(get_direnv_path "$(dirname "$(realpath "$0")")")"

# Determine Claude Code executable
#
CLAUDE_CODE_PATH="$(unmask_executable claude)"

# Launch Claude Code (but only if not called recursively to avoid
# sandboxing the sandbox)
#
if [[ -n "$CLAUDE_CODE_PATH" ]]; then
    if [[ -z "$CLAUDECODE" ]] && [[ -z "$NONO_CAP_FILE" ]]; then
        # Resolve (potentially) critical paths in the environment, as nono will
        # not follow home-manager's symlinks without making all of $HOME
        # readable
        #
        SEP=""
        SANDBOXED_PATH=""
        while IFS=: read -d: -r DIR; do
            if [[ -d "$DIR" ]]; then
                SANDBOXED_PATH="$SANDBOXED_PATH$SEP$(realpath "$DIR")"
                if [[ -z "$SEP" ]]; then
                    SEP=":"
                fi
            fi
        done <<<"${PATH:+"${PATH}:"}"

        SEP=""
        SANDBOXED_MANPATH=""
        while IFS=: read -d: -r DIR; do
            if [[ -d "$DIR" ]]; then
                SANDBOXED_MANPATH="$SANDBOXED_MANPATH$SEP$(realpath "$DIR")"
                if [[ -z "$SEP" ]]; then
                    SEP=":"
                fi
            fi
        done <<<"${MANPATH:+"${MANPATH}:"}"

        SEP=""
        SANDBOXED_TERMINFO_DIRS=""
        while IFS=: read -d: -r DIR; do
            if [[ -d "$DIR" ]]; then
                SANDBOXED_TERMINFO_DIRS="$SANDBOXED_TERMINFO_DIRS$SEP$(realpath "$DIR")"
                if [[ -z "$SEP" ]]; then
                    SEP=":"
                fi
            fi
        done <<<"${TERMINFO_DIRS:+"${TERMINFO_DIRS}:"}"

        SEP=""
        SANDBOXED_XDG_CONFIG_DIRS=""
        while IFS=: read -d: -r DIR; do
            if [[ -d "$DIR" ]]; then
                SANDBOXED_XDG_CONFIG_DIRS="$SANDBOXED_XDG_CONFIG_DIRS$SEP$(realpath "$DIR")"
                if [[ -z "$SEP" ]]; then
                    SEP=":"
                fi
            fi
        done <<<"${XDG_CONFIG_DIRS:+"${XDG_CONFIG_DIRS}:"}"

        SEP=""
        SANDBOXED_XDG_DATA_DIRS=""
        while IFS=: read -d: -r DIR; do
            if [[ -d "$DIR" ]]; then
                SANDBOXED_XDG_DATA_DIRS="$SANDBOXED_XDG_DATA_DIRS$SEP$(realpath "$DIR")"
                if [[ -z "$SEP" ]]; then
                    SEP=":"
                fi
            fi
        done <<<"${XDG_DATA_DIRS:+"${XDG_DATA_DIRS}:"}"

        # Set defaults for XDG variables
        #
        SANDBOXED_XDG_CACHE_HOME="$(realpath "${XDG_CACHE_HOME:-$HOME/.cache}")"
        SANDBOXED_XDG_CONFIG_HOME="$(realpath "${XDG_CONFIG_HOME:-$HOME/.config}")"
        SANDBOXED_XDG_DATA_HOME="$(realpath "${XDG_DATA_HOME:-$HOME/.local/share}")"
        SANDBOXED_XDG_STATE_HOME="$(realpath "${XDG_STATE_HOME:-$HOME/.local/state}")"

        # Information about the ENABLE_LSP_TOOL option:
        #
        #   https://karanbansal.in/blog/claude-code-lsp/
        #   https://github.com/anthropics/claude-code/issues/15619
        #
        # shellcheck disable=SC2046
        env -S \
            $([[ -z "$SANDBOXED_MANPATH" ]] && echo -n "-u MANPATH") \
            $([[ -z "$SANDBOXED_TERMINFO_DIRS" ]] && echo -n "-u TERMINFO_DIRS") \
            $([[ -z "$SANDBOXED_XDG_CONFIG_DIRS" ]] && echo -n "-u XDG_CONFIG_DIRS") \
            $([[ -z "$SANDBOXED_XDG_DATA_DIRS" ]] && echo -n "-u XDG_DATA_DIRS") \
            $([[ -n "$SANDBOXED_MANPATH" ]] && echo -n "MANPATH=\"$SANDBOXED_MANPATH\"") \
            $([[ -n "$SANDBOXED_TERMINFO_DIRS" ]] && echo -n "TERMINFO_DIRS=\"$SANDBOXED_TERMINFO_DIRS\"") \
            $([[ -n "$SANDBOXED_XDG_CONFIG_DIRS" ]] && echo -n "XDG_CONFIG_DIRS=\"$SANDBOXED_XDG_CONFIG_DIRS\"") \
            $([[ -n "$SANDBOXED_XDG_DATA_DIRS" ]] && echo -n "XDG_DATA_DIRS=\"$SANDBOXED_XDG_DATA_DIRS\"") \
            PATH="$SANDBOXED_PATH" \
            XDG_CACHE_HOME="$SANDBOXED_XDG_CACHE_HOME" \
            XDG_CONFIG_HOME="$SANDBOXED_XDG_CONFIG_HOME" \
            XDG_DATA_HOME="$SANDBOXED_XDG_DATA_HOME" \
            XDG_STATE_HOME="$SANDBOXED_XDG_STATE_HOME" \
            CLAUDE_CODE_SHELL="$(realpath $(which bash))" \
            CLAUDE_CODE_EFFORT_LEVEL=max \
            CLAUDE_CODE_USE_POWERSHELL_TOOL=1 \
            ENABLE_LSP_TOOL=1 \
            "$(realpath "$(which nono)")" run \
            --profile "$ENVIRONMENT_PATH"/appdata/nono/profiles/claude-code-sandbox.json \
            --allow "$ENVIRONMENT_PATH" \
            -- "$CLAUDE_CODE_PATH" --dangerously-skip-permissions "$@"
    else
        exec "$CLAUDE_CODE_PATH" "$@"
    fi
else
    echo "Real Claude Code executable not found!"
    exit 1
fi
