#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Claude Code executable
#
CLAUDE_CODE_PATH="$(unmask_executable claude)"

# Resolve (potentially) critical paths in the environment, as nono will
# not follow home-manager's symlinks without making all of $HOME
# readable
#
SEP=""
SANDBOXED_PATH=""
while IFS=: read -d: -r DIR; do
    if [[ -d "$DIR" ]]; then
        SANDBOXED_PATH="$SANDBOXED_PATH$SEP$(realpath "$DIR")"
        if [[ -z "$SEP" ]]; then
            SEP=":"
        fi
    fi
done <<<"${PATH:+"${PATH}:"}"

SEP=""
SANDBOXED_MANPATH=""
while IFS=: read -d: -r DIR; do
    if [[ -d "$DIR" ]]; then
        SANDBOXED_MANPATH="$SANDBOXED_MANPATH$SEP$(realpath "$DIR")"
        if [[ -z "$SEP" ]]; then
            SEP=":"
        fi
    fi
done <<<"${MANPATH:+"${MANPATH}:"}"

SEP=""
SANDBOXED_TERMINFO_DIRS=""
while IFS=: read -d: -r DIR; do
    if [[ -d "$DIR" ]]; then
        SANDBOXED_TERMINFO_DIRS="$SANDBOXED_TERMINFO_DIRS$SEP$(realpath "$DIR")"
        if [[ -z "$SEP" ]]; then
            SEP=":"
        fi
    fi
done <<<"${TERMINFO_DIRS:+"${TERMINFO_DIRS}:"}"

SEP=""
SANDBOXED_XDG_CONFIG_DIRS=""
while IFS=: read -d: -r DIR; do
    if [[ -d "$DIR" ]]; then
        SANDBOXED_XDG_CONFIG_DIRS="$SANDBOXED_XDG_CONFIG_DIRS$SEP$(realpath "$DIR")"
        if [[ -z "$SEP" ]]; then
            SEP=":"
        fi
    fi
done <<<"${XDG_CONFIG_DIRS:+"${XDG_CONFIG_DIRS}:"}"

SEP=""
SANDBOXED_XDG_DATA_DIRS=""
while IFS=: read -d: -r DIR; do
    if [[ -d "$DIR" ]]; then
        SANDBOXED_XDG_DATA_DIRS="$SANDBOXED_XDG_DATA_DIRS$SEP$(realpath "$DIR")"
        if [[ -z "$SEP" ]]; then
            SEP=":"
        fi
    fi
done <<<"${XDG_DATA_DIRS:+"${XDG_DATA_DIRS}:"}"

# Set defaults for XDG variables
#
SANDBOXED_XDG_CACHE_HOME="$(realpath "${XDG_CACHE_HOME:-$HOME/.cache}")"
SANDBOXED_XDG_CONFIG_HOME="$(realpath "${XDG_CONFIG_HOME:-$HOME/.config}")"
SANDBOXED_XDG_DATA_HOME="$(realpath "${XDG_DATA_HOME:-$HOME/.local/share}")"
SANDBOXED_XDG_STATE_HOME="$(realpath "${XDG_STATE_HOME:-$HOME/.local/state}")"

# Launch Claude Code (but only if not called recursively to avoid
# sandboxing the sandbox)
#
if [[ -n "$CLAUDE_CODE_PATH" ]]; then
    if [[ -z "$CLAUDECODE" ]] && [[ -z "$NONO_CAP_FILE" ]]; then
        # FIXME: Figure out the escaping issues below so that I can use
        # `exec` here rather than `eval` (this will also let me stop
        # disabling SC2294, and maybe SC2140)
        #
        # Note that all of the allow/allow-file/read/read-file lines
        # (except for `--allow .`) can be replaced by a custom profile
        # once nono > 0.6.0 is available in nixpkgs-unstable
        #
        # shellcheck disable=SC2046,SC2140,SC2294
        eval env -S \
            $([[ -z "$SANDBOXED_MANPATH" ]] && echo -n "-u MANPATH") \
            $([[ -z "$SANDBOXED_TERMINFO_DIRS" ]] && echo -n "-u TERMINFO_DIRS") \
            $([[ -z "$SANDBOXED_XDG_CONFIG_DIRS" ]] && echo -n "-u XDG_CONFIG_DIRS") \
            $([[ -z "$SANDBOXED_XDG_DATA_DIRS" ]] && echo -n "-u XDG_DATA_DIRS") \
            $([[ -n "$SANDBOXED_MANPATH" ]] && echo -n "MANPATH=\"$SANDBOXED_MANPATH\"") \
            $([[ -n "$SANDBOXED_TERMINFO_DIRS" ]] && echo -n "TERMINFO_DIRS=\"$SANDBOXED_TERMINFO_DIRS\"") \
            $([[ -n "$SANDBOXED_XDG_CONFIG_DIRS" ]] && echo -n "XDG_CONFIG_DIRS=\"$SANDBOXED_XDG_CONFIG_DIRS\"") \
            $([[ -n "$SANDBOXED_XDG_DATA_DIRS" ]] && echo -n "XDG_DATA_DIRS=\"$SANDBOXED_XDG_DATA_DIRS\"") \
            PATH="$SANDBOXED_PATH" \
            XDG_CACHE_HOME="$SANDBOXED_XDG_CACHE_HOME" \
            XDG_CONFIG_HOME="$SANDBOXED_XDG_CONFIG_HOME" \
            XDG_DATA_HOME="$SANDBOXED_XDG_DATA_HOME" \
            XDG_STATE_HOME="$SANDBOXED_XDG_STATE_HOME" \
            CLAUDE_CODE_SHELL="$(realpath $(which bash))" \
            "$(realpath "$(which nono)")" run \
            --profile claude-code \
            --allow "$(get_direnv_path "$(dirname "$(realpath "$0")")")" \
            $([[ -d "$XDG_CACHE_HOME"/go-build ]] && echo -n "--allow $XDG_CACHE_HOME/go-build") \
            $([[ -d "$XDG_CACHE_HOME"/pip ]] && echo -n "--allow $XDG_CACHE_HOME/pip") \
            $([[ -d "$XDG_CACHE_HOME"/pnpm ]] && echo -n "--allow $XDG_CACHE_HOME/pnpm") \
            $([[ -d "$XDG_CACHE_HOME"/uv ]] && echo -n "--allow $XDG_CACHE_HOME/uv") \
            $([[ -d "$XDG_CONFIG_HOME"/go ]] && echo -n "--allow $XDG_CONFIG_HOME/go") \
            $([[ -d "$XDG_DATA_HOME"/pnpm ]] && echo -n "--allow $XDG_DATA_HOME/pnpm") \
            $([[ -d "$XDG_STATE_HOME"/pnpm ]] && echo -n "--allow $XDG_STATE_HOME/pnpm") \
            $([[ -d /tmp ]] && echo -n "--allow /tmp") \
            $([[ -d /var/folders ]] && echo -n "--allow /var/folders") \
            $([[ -e /dev/null ]] && echo -n "--allow-file /dev/null") \
            $([[ -d "$HOME"/.ssh ]] && echo -n "--read $HOME/.ssh") \
            $([[ -d "$HOME"/Library/"Application Support"/Chromium ]] && echo -n "--read $HOME/Library/Application\\ Support/Chromium") \
            $([[ -d "$HOME"/Library/"Application Support"/Google/Chrome ]] && echo -n "--read $HOME/Library/Application\\ Support/Google/Chrome") \
            $([[ -d "$XDG_CONFIG_HOME"/chromium ]] && echo -n "--read $XDG_CONFIG_HOME/chromium") \
            $([[ -d "$XDG_CONFIG_HOME"/git ]] && echo -n "--read $XDG_CONFIG_HOME/git") \
            $([[ -d "$XDG_CONFIG_HOME"/google-chrome ]] && echo -n "--read $XDG_CONFIG_HOME/google-chrome") \
            $([[ -d /etc/skel ]] && echo -n "--read /etc/skel") \
            $([[ -d /nix ]] && echo -n "--read /nix") \
            $([[ -e "$HOME"/.bash_aliases ]] && echo -n "--read-file $HOME/.bash_aliases") \
            $([[ -e /etc/bashrc ]] && echo -n "--read-file /etc/bashrc") \
            -- "$CLAUDE_CODE_PATH" --dangerously-skip-permissions "$@"
    else
        exec "$CLAUDE_CODE_PATH" "$@"
    fi
else
    echo "Real Claude Code executable not found!"
    exit 1
fi
