#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine Anthropic Sandbox Runtime settings path
#
SRT_SETTINGS="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/srt-settings.json

# Determine Goose executable
#
GOOSE_PATH="$(unmask_executable goose)"

# Launch Goose, but in a sandbox
#
if [[ -n "$GOOSE_PATH" ]]; then
    exec srt --settings "$SRT_SETTINGS" "$GOOSE_PATH" "$@"
else
    echo "Real Goose executable not found!"
    exit 1
fi
