#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine mitmdump executable
#
MITM_DUMP_PATH="$(unmask_executable mitmdump)"

# Launch mitmdump CLI
#
if [[ -n "$MITM_DUMP_PATH" ]]; then
    exec "$MITM_DUMP_PATH" --set confdir="$(get_direnv_path "$(dirname "$(realpath "$0")")")"/appdata/mitmproxy "$@"
else
    echo "Real mitmdump executable not found!"
    exit 1
fi
