#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine environment directory
#
ENVIRONMENT_DIRECTORY="$(get_direnv_path "$(dirname "$(realpath "$0")")")"

# Determine msfconsole executable
#
MSFCONSOLE_PATH="$(unmask_executable msfconsole)"

# Run msfconsole
#
if [[ -n "$MSFCONSOLE_PATH" ]]; then
    start_msfdb "$ENVIRONMENT_DIRECTORY"

    "$MSFCONSOLE_PATH" msfConfigRoot="$(get_msf_config_root "$ENVIRONMENT_DIRECTORY")" "$@"

    stop_msfdb "$ENVIRONMENT_DIRECTORY"
else
    echo "Real msfconsole executable not found!"
    exit 1
fi
