#!/usr/bin/env bash

set -e

# Load libenv.sh
#
source "$(dirname "$(realpath "$0")")"/shlib/libenv.sh

# Determine FreeRDP executables
#
X_FREERDP_PATH="$(unmask_executable xfreerdp)"
WAYLAND_FREERDP_PATH="$(unmask_executable wlfreerdp)"
SDL_FREERDP_PATH="$(unmask_executable sdl-freerdp)"

# Determine appropriate FreeRDP implementation
#
if [[ "$(uname -s)" == "Darwin" ]]; then
    FREERDP_PATH="$SDL_FREERDP_PATH"
elif [[ -n "$WAYLAND_DISPLAY" ]] && [[ -n "$WAYLAND_FREERDP_PATH" ]]; then
    FREERDP_PATH="$WAYLAND_FREERDP_PATH"
elif [[ -n "$DISPLAY" ]] && [[ -n "$X_FREERDP_PATH" ]]; then
    FREERDP_PATH="$X_FREERDP_PATH"
elif [[ -n "$SDL_FREERDP_PATH" ]]; then
    FREERDP_PATH="$SDL_FREERDP_PATH"
else
    FREERDP_PATH=""
fi

# Launch FreeRDP client
#
if [[ -n "$FREERDP_PATH" ]]; then
    exec "$FREERDP_PATH" "$@"
else
    echo "An appropriate FreeRDP implementation could not found!"
    exit 1
fi
